"""Export extracted decision trees to C code for embedded RISC-V execution.

Generates two output formats:
  1. **Inline if/else cascade**: A static-inline C function with nested
     if/else statements. Best for very small trees (depth ≤ 3) — the
     compiler inlines everything and produces straight-line branchy code.
  2. **Flat node table**: An array-of-structs representation walked at
     runtime. Better for larger or dynamically-loaded trees.

The generated code uses only:
  - Integer comparisons (no floating-point)
  - Static-const data (no dynamic allocation)
  - No external dependencies

Designed to match the style of `snax_cluster/sw/xai/gradcam/src/gradcam.h`
so it can be dropped into a SNAX application without changes.
"""

from __future__ import annotations

from typing import List

from .rule_extractor import ExtractedRules, TreeNode


def _format_threshold_int(threshold: float, scale: int = 1024) -> int:
    """Quantize a float threshold to fixed-point integer.

    The C kernel works on int32 inputs. Thresholds are scaled by `scale`
    so a comparison `x <= threshold` becomes `(x * scale) <= int_threshold`,
    or equivalently the inputs are pre-scaled to match.

    Args:
        threshold: floating-point threshold from the trained tree
        scale: fixed-point scale factor (default 1024 = ~10 fractional bits)

    Returns:
        Integer threshold
    """
    return int(round(threshold * scale))


def export_to_c_inline(
    rules: ExtractedRules,
    function_name: str = "symbolic_predict",
    input_name: str = "x",
    scale: int = 1024,
) -> str:
    """Export rules as a nested if/else C function.

    Generates code like:
        static inline int32_t symbolic_predict(const int32_t *x) {
            if (x[3] <= 512) {
                if (x[7] <= 1228) {
                    return 0;
                } else {
                    return 2;
                }
            } else {
                return 1;
            }
        }

    Args:
        rules: ExtractedRules to export
        function_name: name for the generated C function
        input_name: name for the input parameter
        scale: fixed-point scale for threshold quantization

    Returns:
        Multi-line C source code as a string
    """
    lines: List[str] = []

    def _walk(node: TreeNode, depth: int) -> None:
        indent = "    " * (depth + 1)
        if node.is_leaf:
            lines.append(f"{indent}return {node.prediction};")
        else:
            int_thresh = _format_threshold_int(node.threshold, scale)
            lines.append(
                f"{indent}if ({input_name}[{node.feature}] <= {int_thresh}) {{"
            )
            _walk(node.left, depth + 1)
            lines.append(f"{indent}}} else {{")
            _walk(node.right, depth + 1)
            lines.append(f"{indent}}}")

    header = (
        f"// Auto-generated by rule_to_c.py — do not edit by hand.\n"
        f"// Decision tree: {rules.n_nodes} nodes, {rules.n_leaves} leaves, "
        f"depth ≤ {rules.max_depth}\n"
        f"// Fixed-point scale: {scale} (thresholds are float * {scale})\n"
        f"// Train fidelity: {rules.train_fidelity:.4f}\n"
        f"static inline int32_t {function_name}(const int32_t *{input_name}) {{"
    )
    lines.insert(0, header)
    _walk(rules.root, 0)
    lines.append("}")
    return "\n".join(lines)


def export_to_c_table(
    rules: ExtractedRules,
    table_name: str = "symbolic_tree",
    function_name: str = "symbolic_predict",
    scale: int = 1024,
) -> str:
    """Export rules as a flat node-table representation.

    Generates a static const struct array plus a walker function:
        typedef struct {
            int8_t  is_leaf;
            int16_t feature;     // input feature index (or prediction if leaf)
            int32_t threshold;   // fixed-point threshold (unused if leaf)
            int16_t left;        // left child node index
            int16_t right;       // right child node index
        } symbolic_node_t;

        static const symbolic_node_t symbolic_tree[N] = { ... };

        static inline int32_t symbolic_predict(const int32_t *x) {
            int16_t i = 0;
            while (!symbolic_tree[i].is_leaf) {
                if (x[symbolic_tree[i].feature] <= symbolic_tree[i].threshold)
                    i = symbolic_tree[i].left;
                else
                    i = symbolic_tree[i].right;
            }
            return symbolic_tree[i].feature;  // leaf stores prediction here
        }

    Args:
        rules: ExtractedRules to export
        table_name: name for the static node table
        function_name: name for the walker function
        scale: fixed-point scale for thresholds

    Returns:
        Multi-line C source code as a string
    """
    # Flatten tree to a list, assigning indices in BFS order
    flat: List[TreeNode] = []
    queue: List[TreeNode] = [rules.root]
    index_map = {}

    while queue:
        node = queue.pop(0)
        index_map[id(node)] = len(flat)
        flat.append(node)
        if not node.is_leaf:
            queue.append(node.left)
            queue.append(node.right)

    # Generate node entries
    entries: List[str] = []
    for node in flat:
        if node.is_leaf:
            # For leaves, store prediction in `feature` field
            entries.append(
                f"    {{ 1, {node.prediction}, 0, -1, -1 }}"
            )
        else:
            int_thresh = _format_threshold_int(node.threshold, scale)
            left_idx = index_map[id(node.left)]
            right_idx = index_map[id(node.right)]
            entries.append(
                f"    {{ 0, {node.feature}, {int_thresh}, "
                f"{left_idx}, {right_idx} }}"
            )

    table_body = ",\n".join(entries)

    code = f"""// Auto-generated by rule_to_c.py — do not edit by hand.
// Decision tree: {rules.n_nodes} nodes, {rules.n_leaves} leaves, depth ≤ {rules.max_depth}
// Fixed-point scale: {scale}
// Train fidelity: {rules.train_fidelity:.4f}

#ifndef SYMBOLIC_NODE_T_DEFINED
#define SYMBOLIC_NODE_T_DEFINED
typedef struct {{
    int8_t  is_leaf;
    int16_t feature;
    int32_t threshold;
    int16_t left;
    int16_t right;
}} symbolic_node_t;
#endif

#define {table_name.upper()}_N_NODES {len(flat)}

static const symbolic_node_t {table_name}[{len(flat)}] = {{
{table_body}
}};

static inline int32_t {function_name}(const int32_t *x) {{
    int16_t i = 0;
    while (!{table_name}[i].is_leaf) {{
        if (x[{table_name}[i].feature] <= {table_name}[i].threshold) {{
            i = {table_name}[i].left;
        }} else {{
            i = {table_name}[i].right;
        }}
    }}
    return {table_name}[i].feature;
}}
"""
    return code


def export_to_c_header(
    rules: ExtractedRules,
    guard_name: str = "SYMBOLIC_RULES_H",
    function_name: str = "symbolic_predict",
    style: str = "inline",
    scale: int = 1024,
) -> str:
    """Wrap the generated C code in a complete header file with include guards.

    Args:
        rules: ExtractedRules to export
        guard_name: include guard macro
        function_name: name for the generated function
        style: 'inline' (nested if/else) or 'table' (flat node table)
        scale: fixed-point scale

    Returns:
        Complete .h file content
    """
    if style == "inline":
        body = export_to_c_inline(rules, function_name=function_name, scale=scale)
    elif style == "table":
        body = export_to_c_table(
            rules, function_name=function_name, scale=scale,
        )
    else:
        raise ValueError(f"Unknown style: {style!r} (use 'inline' or 'table')")

    return f"""#ifndef {guard_name}
#define {guard_name}

#include <stdint.h>

{body}

#endif  // {guard_name}
"""
